### ISSUE TITLE
Adding Dispute Resolution to Upload Documents

### ISSUE THREAD

**Issue by Connor1892** [bcgov/eagle-admin#752]
**As a** EPIC admin user

**I want** to have DR options under the author and milestone dropdowns

**so that** I am able to upload documents connected to Dispute Resolution

### Scenario 1: 

GIVEN I am uploading a DR document
WHEN I select the author dropdown
THEN I have the option to select: "Dispute Resolution Facilitator"

### Scenario 2:

GIVEN I am uploading a DR document
WHEN I select the milestone dropdown
THEN I have the option to select: "Dispute Resolution"

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by EAO-App-Admin** [comment]
Tested and working as intended
